-- ---> Core plugins
require 'core/plugins'
require 'core/treesitter'
require 'core/keymaps'
require 'core/autopairs'
require 'core/cmp'
require 'core/gitsigns'
require 'core/lenservers'
require 'core/lpssignature'
require 'core/lspsaga'
require 'core/luasnips'
require 'core/terminal'
require 'core/settings'
require 'core/trouble'

-- ---> Utils plugins
require 'utils/colorscheme'
require 'utils/bufferline'
require 'utils/colorizer'
require 'utils/staline'
require 'utils/comment'
require 'utils/nvimtree'
require 'utils/telescope'
require 'utils/whichkey'
require 'utils/zenmode'
require 'utils/betterscape'
require 'utils/dashboard'
require 'utils/indentline'
